# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('boxscore_url', models.TextField()),
                ('awayteam_name', models.CharField(max_length=100)),
                ('hometeam_name', models.CharField(max_length=100)),
            ],
        ),
    ]
