# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='worth_watching',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
