# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import datetime


def migrate_time_to_proper_date(apps, schema_editor):
    Game = apps.get_model("app", "Game")

    for game in Game.objects.all():
        # Month Day, Year
        if game.time[0].isdigit():
            game.date = datetime.datetime.strptime(game.time, '%d/%m/%Y')
        else:
            game.date = datetime.datetime.strptime(game.time, '%B %d, %Y')
        game.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_game_worth_watching'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_time_to_proper_date),
    ]